lean koi

diff --git a/.local/scripts/bin/koi b/.local/scripts/bin/koi
--- a/.local/scripts/bin/koi
+++ b/.local/scripts/bin/koi
@@ -8,31 +8,11 @@ installed() {
 }
 
 installed hurl "Missing dependency: hurl"
+installed jnv "Missing dependency: jnv"
+installed fzf "Missing dependency: fzf"
 
 isdarwin() {
 	uname | grep -i darwin
-}
-
-usage() {
-	cat - <<-"EOF"
-	Usage:
-	koi.sh -f <file> [-x <hurl arg>]
-
-	Flags:
-	-h             help
-	-f <file>      hurl file to execute
-	-x <flag>      hurl flag to append
-	-X             no postprocessing, just run the request and return the bare response
-	               (this also enables the -i hurl flag)
-
-	Examples:
-	koi.sh -h                                 # show this message
-	koi.sh -f create.hurl                     # run file (default hurl flags: --color --error-format=long)
-	koi.sh -f create.hurl -x --ignore-asserts # final hurl args: --color --error-format=long --ignore-asserts
-	koi.sh -f create.hurl -x -x               # final hurl args: --color --error-format=long -x
-	koi.sh <file>                             # same as `koi.sh -f <file>`
-	EOF
-	exit 1
 }
 
 date="date"
@@ -45,38 +25,15 @@ if ! command -v "$date" &>/dev/null; then
 	exit 1
 fi
 
-[ $# -eq 0 ] && usage
-[ $# -eq 1 ] && FILE="$1"
-NO_POSTPROCESSING=0
-HURL_ARGS=(--error-format=long)
-while true; do
-	[ -z "$1" ] && break
+q="$@"
+if [ "$#" -eq 1 ] && [ -f "$1" ]; then
+  FILE="$1"
+else
+  FILE="$(find . -iname '*.hurl' | fzf -q "$q" -1)"
+fi
 
-	case "$1" in
-		-h|--help)
-			usage
-			;;
-
-		-X)
-			NO_POSTPROCESSING=1
-			HURL_ARGS+=("-i")
-			;;
-
-		-f)
-			shift
-			FILE="$1"
-			;;
-
-		-x)
-			shift
-			HURL_ARGS+=("$1")
-	esac
-
-	shift
-done
-
-if [ -z "$FILE" ]; then
-	echo "Missing file." >&2
+if [ ! -f "$FILE" ]; then
+	echo "Could not open file." >&2
 	exit 1
 fi
 
@@ -98,19 +55,16 @@ export HURL_KOI_UUID
 export HURL_KOI_RANDOM
 export HURL_KOI_LOREM
 
-output=$(hurl --include "${HURL_ARGS[@]}" "$FILE") || exit
+output=$(hurl --include "$FILE") || exit
 
-if [ "$NO_POSTPROCESSING" -eq 1 ]; then
-	echo "$output"
-	exit
-fi
-
-ft="silent set ft"
-grep -iq "content-type: text/html" <<< "$output" && ft="set ft=html"
-grep -iq "content-type: application/json" <<< "$output" && ft="set ft=json"
-
-if grep -iq -e "content-type: application/json" -e "HTTP.* 200" <<< "$output"; then
-  echo "$output" | awk '/^\s*$/ { headers_done=1 } headers_done {print}' | nvim -c 'set cmdheight=1' -c 'set buftype=nofile' -c 'set ft=json' -c '%!jq .'
+if grep -iq "content-type: application/json" <<< "$output"; then
+  echo "$output" | awk 'headers_end{print} /^\s*$/{headers_end=1}' | jnv
+  echo
+  echo
+  echo -e "$output"
 else
+  ft="set ft=http"
+  grep -i "content-type: text/html" <<< "$output" && ft="set ft=html"
+
   echo "$output" | nvim -c 'set cmdheight=1' -c 'set buftype=nofile' -c "$ft"
 fi
